### ISSUE TITLE
is there a layer limit?

### ISSUE THREAD

**Issue by nmz787** [trilomix/GDS3D#11]
the original press release, at least the one I found, says "up to 7 metal layers" (https://www.utwente.nl/en/news/2012/3/59583/3d-gdsii-viewer-goes-open-source)

Is there an inherent codified limit? I'm dealing with about 2-3x that in some cases.

**Comment by trilomix** [comment]
Hello nmz787, :-)

There is no limit regarding number of layers and so number of metal layers.

Regards,

Trilomix
