### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by horror-vacui** [trilomix/GDS3D#3]
Is there any way to change the black background color? I would like to use white background for nice screenshots for documentation.

**Comment by horror-vacui** [comment]
A possible workaround if it is only needed for documentation: swap the colors with your favorite image editor: gimp, imagemagick, etc.

Example:
`convert Screenshot_GDS3D.png -fuzz 0 -fill white -opaque black tmp.png`

**Comment by trilomix** [comment]
Hello, I change the background to transparent so you can put what ever you want behind your snapshot!
